[tool.poetry]
name = "hng12-backend-task"
version = "0.1.0"
description = ""
authors = ["Agimuche <Agimuche1@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
# Add other dependencies below

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
